name: checkov

on:
  pull_request:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          soft_fail: true
          # This will add both a CLI output to the console and create a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: download satif-to-rdjson
        run: |
          curl -Lo sarif-to-rdjson.tar.gz https://github.com/yteraoka/sarif-to-rdjson/releases/download/v0.0.5/sarif-to-rdjson_Linux_x86_64.tar.gz
          tar -zxvf sarif-to-rdjson.tar.gz sarif-to-rdjson
          chmod +x sarif-to-rdjson

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./sarif-to-rdjson results.sarif | reviewdog -f=rdjson -name=checkov -reporter=github-pr-review -fail-on-error=false
